services:
  greenhouse-emulator:
    build: .
    ports:
      - "30103:30103"
      - "5432:5432"
    environment:
      DB_HOST: "host.docker.internal"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASS: "1234"
      DB_NAME: "test"
      LOG_LEVEL: "DEBUG"
      LOG_FORMAT: "PLAIN"
      API_SERVER_HOST: "0.0.0.0"
      API_SERVER_PORT: "30303"
      GREENHOUSE_SERVICE: "http://localhost:30103"
      ASSESSMENT_SERVICE: "http://localhost:30203"
    restart: unless-stopped
