services:
  assessment-emulator:
    build: .
    ports:
      - "30203:30203"
    environment:
      LOG_LEVEL: "DEBUG"
      LOG_FORMAT: "PLAIN"
      API_SERVER_HOST: "0.0.0.0"
      API_SERVER_PORT: "30203"
    restart: unless-stopped
